metadata:
  base_dir: /scratch.local/cmc-s3-bucket/
  resolution_microns:
  - 5.0
  - 5.0
  - 3.4
  scan_resolution:
  - 0.01
  - 0.01
  tile_overlap: 0.1
  tile_width: 1000
  tile_height: 1000
  depth: 191 
tiles:
- filepath: slice_150_tile_001_Cross.mat
  tile_number: 1
  x: 0.0
  y: 0.0
- filepath: slice_150_tile_002_Cross.mat
  tile_number: 2
  x: 900.0
  y: 0.0
- filepath: slice_150_tile_003_Cross.mat
  tile_number: 3
  x: 1800.0
  y: 0.0
- filepath: slice_150_tile_004_Cross.mat
  tile_number: 4
  x: 2700.0
  y: 0.0
- filepath: slice_150_tile_005_Cross.mat
  tile_number: 5
  x: 3600.0
  y: 0.0
- filepath: slice_150_tile_006_Cross.mat
  tile_number: 6
  x: 4500.0
  y: 0.0
- filepath: slice_150_tile_007_Cross.mat
  tile_number: 7
  x: 5400.0
  y: 0.0
- filepath: slice_150_tile_008_Cross.mat
  tile_number: 8
  x: 6300.0
  y: 0.0
- filepath: slice_150_tile_009_Cross.mat
  tile_number: 9
  x: 7200.0
  y: 0.0
- filepath: slice_150_tile_010_Cross.mat
  tile_number: 10
  x: 8100.0
  y: 0.0
- filepath: slice_150_tile_011_Cross.mat
  tile_number: 11
  x: 9000.0
  y: 0.0
- filepath: slice_150_tile_012_Cross.mat
  tile_number: 12
  x: 9900.0
  y: 0.0
- filepath: slice_150_tile_013_Cross.mat
  tile_number: 13
  x: 10800.0
  y: 0.0
- filepath: slice_150_tile_014_Cross.mat
  tile_number: 14
  x: 11700.0
  y: 0.0
- filepath: slice_150_tile_015_Cross.mat
  tile_number: 15
  x: 0.0
  y: 900.0
- filepath: slice_150_tile_016_Cross.mat
  tile_number: 16
  x: 900.0
  y: 900.0
- filepath: slice_150_tile_017_Cross.mat
  tile_number: 17
  x: 1800.0
  y: 900.0
- filepath: slice_150_tile_018_Cross.mat
  tile_number: 18
  x: 2700.0
  y: 900.0
- filepath: slice_150_tile_019_Cross.mat
  tile_number: 19
  x: 3600.0
  y: 900.0
- filepath: slice_150_tile_020_Cross.mat
  tile_number: 20
  x: 4500.0
  y: 900.0
- filepath: slice_150_tile_021_Cross.mat
  tile_number: 21
  x: 5400.0
  y: 900.0
- filepath: slice_150_tile_022_Cross.mat
  tile_number: 22
  x: 6300.0
  y: 900.0
- filepath: slice_150_tile_023_Cross.mat
  tile_number: 23
  x: 7200.0
  y: 900.0
- filepath: slice_150_tile_024_Cross.mat
  tile_number: 24
  x: 8100.0
  y: 900.0
- filepath: slice_150_tile_025_Cross.mat
  tile_number: 25
  x: 9000.0
  y: 900.0
- filepath: slice_150_tile_026_Cross.mat
  tile_number: 26
  x: 9900.0
  y: 900.0
- filepath: slice_150_tile_027_Cross.mat
  tile_number: 27
  x: 10800.0
  y: 900.0
- filepath: slice_150_tile_028_Cross.mat
  tile_number: 28
  x: 11700.0
  y: 900.0
- filepath: slice_150_tile_029_Cross.mat
  tile_number: 29
  x: 0.0
  y: 1800.0
- filepath: slice_150_tile_030_Cross.mat
  tile_number: 30
  x: 900.0
  y: 1800.0
- filepath: slice_150_tile_031_Cross.mat
  tile_number: 31
  x: 1800.0
  y: 1800.0
- filepath: slice_150_tile_032_Cross.mat
  tile_number: 32
  x: 2700.0
  y: 1800.0
- filepath: slice_150_tile_033_Cross.mat
  tile_number: 33
  x: 3600.0
  y: 1800.0
- filepath: slice_150_tile_034_Cross.mat
  tile_number: 34
  x: 4500.0
  y: 1800.0
- filepath: slice_150_tile_035_Cross.mat
  tile_number: 35
  x: 5400.0
  y: 1800.0
- filepath: slice_150_tile_036_Cross.mat
  tile_number: 36
  x: 6300.0
  y: 1800.0
- filepath: slice_150_tile_037_Cross.mat
  tile_number: 37
  x: 7200.0
  y: 1800.0
- filepath: slice_150_tile_038_Cross.mat
  tile_number: 38
  x: 8100.0
  y: 1800.0
- filepath: slice_150_tile_039_Cross.mat
  tile_number: 39
  x: 9000.0
  y: 1800.0
- filepath: slice_150_tile_040_Cross.mat
  tile_number: 40
  x: 9900.0
  y: 1800.0
- filepath: slice_150_tile_041_Cross.mat
  tile_number: 41
  x: 10800.0
  y: 1800.0
- filepath: slice_150_tile_042_Cross.mat
  tile_number: 42
  x: 11700.0
  y: 1800.0
- filepath: slice_150_tile_043_Cross.mat
  tile_number: 43
  x: 0.0
  y: 2700.0
- filepath: slice_150_tile_044_Cross.mat
  tile_number: 44
  x: 900.0
  y: 2700.0
- filepath: slice_150_tile_045_Cross.mat
  tile_number: 45
  x: 1800.0
  y: 2700.0
- filepath: slice_150_tile_046_Cross.mat
  tile_number: 46
  x: 2700.0
  y: 2700.0
- filepath: slice_150_tile_047_Cross.mat
  tile_number: 47
  x: 3600.0
  y: 2700.0
- filepath: slice_150_tile_048_Cross.mat
  tile_number: 48
  x: 4500.0
  y: 2700.0
- filepath: slice_150_tile_049_Cross.mat
  tile_number: 49
  x: 5400.0
  y: 2700.0
- filepath: slice_150_tile_050_Cross.mat
  tile_number: 50
  x: 6300.0
  y: 2700.0
- filepath: slice_150_tile_051_Cross.mat
  tile_number: 51
  x: 7200.0
  y: 2700.0
- filepath: slice_150_tile_052_Cross.mat
  tile_number: 52
  x: 8100.0
  y: 2700.0
- filepath: slice_150_tile_053_Cross.mat
  tile_number: 53
  x: 9000.0
  y: 2700.0
- filepath: slice_150_tile_054_Cross.mat
  tile_number: 54
  x: 9900.0
  y: 2700.0
- filepath: slice_150_tile_055_Cross.mat
  tile_number: 55
  x: 10800.0
  y: 2700.0
- filepath: slice_150_tile_056_Cross.mat
  tile_number: 56
  x: 11700.0
  y: 2700.0
- filepath: slice_150_tile_057_Cross.mat
  tile_number: 57
  x: 0.0
  y: 3600.0
- filepath: slice_150_tile_058_Cross.mat
  tile_number: 58
  x: 900.0
  y: 3600.0
- filepath: slice_150_tile_059_Cross.mat
  tile_number: 59
  x: 1800.0
  y: 3600.0
- filepath: slice_150_tile_060_Cross.mat
  tile_number: 60
  x: 2700.0
  y: 3600.0
- filepath: slice_150_tile_061_Cross.mat
  tile_number: 61
  x: 3600.0
  y: 3600.0
- filepath: slice_150_tile_062_Cross.mat
  tile_number: 62
  x: 4500.0
  y: 3600.0
- filepath: slice_150_tile_063_Cross.mat
  tile_number: 63
  x: 5400.0
  y: 3600.0
- filepath: slice_150_tile_064_Cross.mat
  tile_number: 64
  x: 6300.0
  y: 3600.0
- filepath: slice_150_tile_065_Cross.mat
  tile_number: 65
  x: 7200.0
  y: 3600.0
- filepath: slice_150_tile_066_Cross.mat
  tile_number: 66
  x: 8100.0
  y: 3600.0
- filepath: slice_150_tile_067_Cross.mat
  tile_number: 67
  x: 9000.0
  y: 3600.0
- filepath: slice_150_tile_068_Cross.mat
  tile_number: 68
  x: 9900.0
  y: 3600.0
- filepath: slice_150_tile_069_Cross.mat
  tile_number: 69
  x: 10800.0
  y: 3600.0
- filepath: slice_150_tile_070_Cross.mat
  tile_number: 70
  x: 11700.0
  y: 3600.0
- filepath: slice_150_tile_071_Cross.mat
  tile_number: 71
  x: 0.0
  y: 4500.0
- filepath: slice_150_tile_072_Cross.mat
  tile_number: 72
  x: 900.0
  y: 4500.0
- filepath: slice_150_tile_073_Cross.mat
  tile_number: 73
  x: 1800.0
  y: 4500.0
- filepath: slice_150_tile_074_Cross.mat
  tile_number: 74
  x: 2700.0
  y: 4500.0
- filepath: slice_150_tile_075_Cross.mat
  tile_number: 75
  x: 3600.0
  y: 4500.0
- filepath: slice_150_tile_076_Cross.mat
  tile_number: 76
  x: 4500.0
  y: 4500.0
- filepath: slice_150_tile_077_Cross.mat
  tile_number: 77
  x: 5400.0
  y: 4500.0
- filepath: slice_150_tile_078_Cross.mat
  tile_number: 78
  x: 6300.0
  y: 4500.0
- filepath: slice_150_tile_079_Cross.mat
  tile_number: 79
  x: 7200.0
  y: 4500.0
- filepath: slice_150_tile_080_Cross.mat
  tile_number: 80
  x: 8100.0
  y: 4500.0
- filepath: slice_150_tile_081_Cross.mat
  tile_number: 81
  x: 9000.0
  y: 4500.0
- filepath: slice_150_tile_082_Cross.mat
  tile_number: 82
  x: 9900.0
  y: 4500.0
- filepath: slice_150_tile_083_Cross.mat
  tile_number: 83
  x: 10800.0
  y: 4500.0
- filepath: slice_150_tile_084_Cross.mat
  tile_number: 84
  x: 11700.0
  y: 4500.0
- filepath: slice_150_tile_085_Cross.mat
  tile_number: 85
  x: 0.0
  y: 5400.0
- filepath: slice_150_tile_086_Cross.mat
  tile_number: 86
  x: 900.0
  y: 5400.0
- filepath: slice_150_tile_087_Cross.mat
  tile_number: 87
  x: 1800.0
  y: 5400.0
- filepath: slice_150_tile_088_Cross.mat
  tile_number: 88
  x: 2700.0
  y: 5400.0
- filepath: slice_150_tile_089_Cross.mat
  tile_number: 89
  x: 3600.0
  y: 5400.0
- filepath: slice_150_tile_090_Cross.mat
  tile_number: 90
  x: 4500.0
  y: 5400.0
- filepath: slice_150_tile_091_Cross.mat
  tile_number: 91
  x: 5400.0
  y: 5400.0
- filepath: slice_150_tile_092_Cross.mat
  tile_number: 92
  x: 6300.0
  y: 5400.0
- filepath: slice_150_tile_093_Cross.mat
  tile_number: 93
  x: 7200.0
  y: 5400.0
- filepath: slice_150_tile_094_Cross.mat
  tile_number: 94
  x: 8100.0
  y: 5400.0
- filepath: slice_150_tile_095_Cross.mat
  tile_number: 95
  x: 9000.0
  y: 5400.0
- filepath: slice_150_tile_096_Cross.mat
  tile_number: 96
  x: 9900.0
  y: 5400.0
- filepath: slice_150_tile_097_Cross.mat
  tile_number: 97
  x: 10800.0
  y: 5400.0
- filepath: slice_150_tile_098_Cross.mat
  tile_number: 98
  x: 11700.0
  y: 5400.0
- filepath: slice_150_tile_099_Cross.mat
  tile_number: 99
  x: 0.0
  y: 6300.0
- filepath: slice_150_tile_100_Cross.mat
  tile_number: 100
  x: 900.0
  y: 6300.0
- filepath: slice_150_tile_101_Cross.mat
  tile_number: 101
  x: 1800.0
  y: 6300.0
- filepath: slice_150_tile_102_Cross.mat
  tile_number: 102
  x: 2700.0
  y: 6300.0
- filepath: slice_150_tile_103_Cross.mat
  tile_number: 103
  x: 3600.0
  y: 6300.0
- filepath: slice_150_tile_104_Cross.mat
  tile_number: 104
  x: 4500.0
  y: 6300.0
- filepath: slice_150_tile_105_Cross.mat
  tile_number: 105
  x: 5400.0
  y: 6300.0
- filepath: slice_150_tile_106_Cross.mat
  tile_number: 106
  x: 6300.0
  y: 6300.0
- filepath: slice_150_tile_107_Cross.mat
  tile_number: 107
  x: 7200.0
  y: 6300.0
- filepath: slice_150_tile_108_Cross.mat
  tile_number: 108
  x: 8100.0
  y: 6300.0
- filepath: slice_150_tile_109_Cross.mat
  tile_number: 109
  x: 9000.0
  y: 6300.0
- filepath: slice_150_tile_110_Cross.mat
  tile_number: 110
  x: 9900.0
  y: 6300.0
- filepath: slice_150_tile_111_Cross.mat
  tile_number: 111
  x: 10800.0
  y: 6300.0
- filepath: slice_150_tile_112_Cross.mat
  tile_number: 112
  x: 11700.0
  y: 6300.0
- filepath: slice_150_tile_113_Cross.mat
  tile_number: 113
  x: 0.0
  y: 7200.0
- filepath: slice_150_tile_114_Cross.mat
  tile_number: 114
  x: 900.0
  y: 7200.0
- filepath: slice_150_tile_115_Cross.mat
  tile_number: 115
  x: 1800.0
  y: 7200.0
- filepath: slice_150_tile_116_Cross.mat
  tile_number: 116
  x: 2700.0
  y: 7200.0
- filepath: slice_150_tile_117_Cross.mat
  tile_number: 117
  x: 3600.0
  y: 7200.0
- filepath: slice_150_tile_118_Cross.mat
  tile_number: 118
  x: 4500.0
  y: 7200.0
- filepath: slice_150_tile_119_Cross.mat
  tile_number: 119
  x: 5400.0
  y: 7200.0
- filepath: slice_150_tile_120_Cross.mat
  tile_number: 120
  x: 6300.0
  y: 7200.0
- filepath: slice_150_tile_121_Cross.mat
  tile_number: 121
  x: 7200.0
  y: 7200.0
- filepath: slice_150_tile_122_Cross.mat
  tile_number: 122
  x: 8100.0
  y: 7200.0
- filepath: slice_150_tile_123_Cross.mat
  tile_number: 123
  x: 9000.0
  y: 7200.0
- filepath: slice_150_tile_124_Cross.mat
  tile_number: 124
  x: 9900.0
  y: 7200.0
- filepath: slice_150_tile_125_Cross.mat
  tile_number: 125
  x: 10800.0
  y: 7200.0
- filepath: slice_150_tile_126_Cross.mat
  tile_number: 126
  x: 11700.0
  y: 7200.0
